# Build artifacts for the unpins website.
#
# Layout (everything served lives at repo root; Wrangler reads `.assetsignore`
# to skip the build scripts during deploy):
#   index.html, styles.css   → sources, edited directly, served as-is
#   unpins-logo.svg          → generated by `make logo`, committed
#   packages.html            → generated by `make packages`, committed
#   logo/, gen-packages.py   → build scripts, excluded from deploy
#   target/                  → font + dev PNG (gitignored, excluded)
#
# Targets:
#   all       — logo SVG + dev preview PNG (default)
#   logo      — unpins-logo.svg + target/unpins-logo.png
#   packages  — packages.html (needs nix; run manually when versions change)
#   clean     — remove target/ and the generated logo SVG (keep packages.html,
#               which is committed and not regenerated by default `make`)
#
# Dependencies: python3 + fontTools, inkscape, curl, unzip; nix (for packages).

TARGET   := target
FONT_DIR := $(TARGET)/fonts
FONT_TTF := $(FONT_DIR)/fonts/ttf/JetBrainsMono-Bold.ttf
FONT_VER := 2.304
FONT_URL := https://github.com/JetBrains/JetBrainsMono/releases/download/v$(FONT_VER)/JetBrainsMono-$(FONT_VER).zip

LOGO_SVG       := unpins-logo.svg
LOGO_PNG       := $(TARGET)/unpins-logo.png
LOGO_PNG_WIDTH := 1600

.PHONY: all logo packages clean
.DEFAULT_GOAL := all

all: logo

logo: $(LOGO_PNG)

$(FONT_TTF):
	@echo "→ Downloading JetBrains Mono $(FONT_VER)..."
	@mkdir -p $(FONT_DIR)
	@curl -sL -o $(FONT_DIR)/JetBrainsMono.zip $(FONT_URL)
	@cd $(FONT_DIR) && unzip -oq JetBrainsMono.zip
	@rm $(FONT_DIR)/JetBrainsMono.zip

$(LOGO_SVG): logo/build-logo.py $(FONT_TTF)
	@echo "→ Building logo SVG..."
	@FONT_PATH=$(abspath $(FONT_TTF)) OUT_SVG=$(abspath $(LOGO_SVG)) python3 logo/build-logo.py

$(LOGO_PNG): $(LOGO_SVG)
	@echo "→ Rendering logo PNG..."
	@inkscape --export-type=png --export-width=$(LOGO_PNG_WIDTH) $(LOGO_SVG) -o $(LOGO_PNG) 2>/dev/null

packages:
	@echo "→ Regenerating packages.html..."
	@python3 gen-packages.py

clean:
	@rm -rf $(TARGET)
	@rm -f $(LOGO_SVG)
