# Build artifacts for the unpins website.
#
# Layout (everything served lives at repo root; Wrangler reads `.assetsignore`
# to skip the build scripts during deploy):
#   index.html, styles.css   → sources, edited directly, served as-is
#   unpins-logo.svg          → hand-edited source, served as-is
#   favicon.svg              → hand-edited source, served as-is
#   packages.html            → generated by `make packages`, committed
#   og-banner.svg            → hand-edited source for og.png, excluded from deploy
#   og.png                   → generated by `make og`, committed (og:image)
#   gen-packages.py          → build script, excluded from deploy
#   target/                  → dev PNG (gitignored, excluded)
#
# Targets:
#   all       — dev preview PNG of the logo (default)
#   logo      — target/unpins-logo.png
#   og        — og.png (run manually when og-banner.svg changes)
#   packages  — packages.html (needs nix; run manually when versions change)
#   status    — status.html CI dashboard (run when a package is added/removed)
#   clean     — remove target/
#
# Dependencies: inkscape; nix (for packages).

TARGET   := target

LOGO_SVG       := unpins-logo.svg
LOGO_PNG       := $(TARGET)/unpins-logo.png
LOGO_PNG_WIDTH := 1600

OG_SVG := og-banner.svg
OG_PNG := og.png

.PHONY: all logo og packages status clean
.DEFAULT_GOAL := all

all: logo

logo: $(LOGO_PNG)

og: $(OG_PNG)

$(OG_PNG): $(OG_SVG)
	@echo "→ Rendering og:image banner..."
	@inkscape --export-type=png --export-width=1200 --export-height=630 $(OG_SVG) -o $(OG_PNG) 2>/dev/null

$(LOGO_PNG): $(LOGO_SVG)
	@echo "→ Rendering logo PNG..."
	@mkdir -p $(TARGET)
	@inkscape --export-type=png --export-width=$(LOGO_PNG_WIDTH) $(LOGO_SVG) -o $(LOGO_PNG) 2>/dev/null

packages:
	@echo "→ Regenerating packages.html..."
	@python3 gen-packages.py

status:
	@echo "→ Regenerating status.html..."
	@python3 gen-status.py

clean:
	@rm -rf $(TARGET)
